outputTopicPrefix: raw
dlqTopic: streaming-dead-letters
replicaCount: 1
image:
  repository: smartcitiesdata/reaper
  tag: development
  pullPolicy: Always
service:
  port: 9092
  type: ClusterIP

aws:
  region: us-west-2
  hostedFileBucket: ""

redis:
  host: redis.external-services
  password: ""
  
strimzi:
  kafka:
    brokers: streaming-service-kafka-bootstrap.streaming-prime:9092
vault:
  endpoint: http://vault.vault:8200

resources:
  limits:
    memory: 1Gi
    cpu: 300m
    ephemeral-storage: 15G
  requests:
    memory: 512Mi
    cpu: 100m
    ephemeral-storage: 10G
