replicaCount: 3

service:
  name: discovery-api
  type: NodePort
  port: 80
  auth_string: ""

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  security_groups: ""
  dnsZone: "localhost"
  rootDnsZone: "localhost"
  certificate_arn: ""

image:
  name: smartcitiesdata/discovery_api
  tag: development
  pullPolicy: Always

monitoring:
  targetPort: 80

nodeSelector: {}
tolerations: []
affinity: {}

kafka:
  #comma delimited list of kafka seed brokers
  brokers: streaming-service-kafka-bootstrap.streaming-prime:9092

redis:
  host: discovery-api-redis-master
  password: ""

presto:
  url: "http://presto-endpoint:8080"
  catalog: "hive"
  schema: "default"

ldap:
  host: "ldap.example.com"
  base: "dc=example,dc=com"
  user: "binduser"
  account:
    subdn: "cn=users,cn=accounts"

s3:
  hostedFileBucket: "hosted-dataset-files"
  hostedFileRegion: "us-west-2"

vault:
  endpoint: http://vault.example.com:8200

postgres:
  host: "example.com"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "password"

auth:
  jwt_issuer: ""
  jwks_endpoint: ""
  user_info_endpoint: ""
