dependencies:
  - name: openldap
    version: 1.2.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: openldap.enabled
  - name: andi
    version: 1.1.2
    repository: http://localhost:8879
    condition: andi.enabled
  - name: discovery-api
    version: 0.4.3
    repository: http://localhost:8879
    condition: discovery-api.enabled
  - name: discovery-streams
    version: 0.1.4
    repository: https://smartcitiesdata.github.io/charts
    condition: discovery-streams.enabled
  - name: flair
    version: 2.1.0
    repository: https://smartcitiesdata.github.io/charts
    condition: flair.enabled
  - name: forklift
    version: 2.4.0
    repository: http://localhost:8879
    condition: forklift.enabled
  - name: kubernetes-data-platform
    version: 1.1.1
    repository: https://raw.githubusercontent.com/PillarTechnology/charts-1/master/docs
    condition: kubernetes-data-platform.enabled
  - name: odo
    version: 0.2.2
    repository: https://smartcitiesdata.github.io/charts
    condition: odo.enabled
  - name: reaper
    version: 0.1.1
    repository: http://localhost:8879
    condition: reaper.enabled
  - name: redis
    version: 9.5.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: valkyrie
    version: 2.4.0
    repository: http://localhost:8879
    condition: valkyrie.enabled
